-- ESCO ICT knowledge concepts (ESCO v1.2.1, English, skills_en.csv).
--
-- V10 seeded only skillType = 'skill/competence', which in ESCO excludes
-- every technology: Java, Python, SQL and JavaScript are all classified as
-- 'knowledge'. That left candidates unable to select any technology at all.
--
-- This adds the knowledge concepts under ISCED-F field 06 (information and
-- communication technologies), reached through broaderRelationsSkillPillar.
-- A hierarchy branch was chosen over digitalSkillsCollection because it is a
-- principled cut rather than a curated DigComp list, and because 745 of that
-- collection's 1,284 rows are competences V10 already seeded.
--
-- Note: ESCO v1.2.1 has no Docker, React, Kubernetes or HTML concept under any
-- filter. It is a labour-market taxonomy, not a tech-stack one.
-- 365 rows, already deduplicated against the V10 seed.

INSERT INTO skills (name, created_at, updated_at) VALUES
    ('ABAP', NOW(), NOW()),
    ('ABBYY FineReader', NOW(), NOW()),
    ('Absorb (learning management systems)', NOW(), NOW()),
    ('adobe creative suite', NOW(), NOW()),
    ('Adobe Illustrator', NOW(), NOW()),
    ('Adobe Photoshop', NOW(), NOW()),
    ('Adobe Photoshop Lightroom', NOW(), NOW()),
    ('advanced driver assistant systems', NOW(), NOW()),
    ('Agile development', NOW(), NOW()),
    ('Aircrack (penetration testing tool)', NOW(), NOW()),
    ('AJAX', NOW(), NOW()),
    ('Ajax Framework', NOW(), NOW()),
    ('algorithms', NOW(), NOW()),
    ('Android (mobile operating systems)', NOW(), NOW()),
    ('Angular', NOW(), NOW()),
    ('Ansible', NOW(), NOW()),
    ('Apache Maven', NOW(), NOW()),
    ('Apache Tomcat', NOW(), NOW()),
    ('APL', NOW(), NOW()),
    ('application usability', NOW(), NOW()),
    ('artificial neural networks', NOW(), NOW()),
    ('ASP.NET', NOW(), NOW()),
    ('Assembly (computer programming)', NOW(), NOW()),
    ('assessment of risks and threats', NOW(), NOW()),
    ('ATM systems', NOW(), NOW()),
    ('attack vectors', NOW(), NOW()),
    ('audio editing software', NOW(), NOW()),
    ('augmented reality', NOW(), NOW()),
    ('authoring software', NOW(), NOW()),
    ('automatic control system', NOW(), NOW()),
    ('automatic meter reading', NOW(), NOW()),
    ('Backbox (penetration testing tool)', NOW(), NOW()),
    ('BlackArch', NOW(), NOW()),
    ('BlackBerry', NOW(), NOW()),
    ('blockchain', NOW(), NOW()),
    ('blockchain application areas', NOW(), NOW()),
    ('blockchain applications', NOW(), NOW()),
    ('blockchain applications security principles', NOW(), NOW()),
    ('blockchain architecture', NOW(), NOW()),
    ('blockchain components', NOW(), NOW()),
    ('blockchain concept application', NOW(), NOW()),
    ('blockchain consensus mechanisms', NOW(), NOW()),
    ('blockchain design patterns', NOW(), NOW()),
    ('blockchain history', NOW(), NOW()),
    ('blockchain mining principles', NOW(), NOW()),
    ('blockchain openness', NOW(), NOW()),
    ('blockchain platforms', NOW(), NOW()),
    ('blockchain signature schemes', NOW(), NOW()),
    ('blockchain terminology', NOW(), NOW()),
    ('blockchain-based business models', NOW(), NOW()),
    ('blockchain-based services regulation', NOW(), NOW()),
    ('Brightspace (learning management systems)', NOW(), NOW()),
    ('business ICT systems', NOW(), NOW()),
    ('C#', NOW(), NOW()),
    ('C++', NOW(), NOW()),
    ('CA Datacom/DB', NOW(), NOW()),
    ('CAD for footwear', NOW(), NOW()),
    ('CAD software', NOW(), NOW()),
    ('CADD software', NOW(), NOW()),
    ('CAE software', NOW(), NOW()),
    ('Cain and Abel (penetration testing tool)', NOW(), NOW()),
    ('call routing', NOW(), NOW()),
    ('call-centre technologies', NOW(), NOW()),
    ('CAM software', NOW(), NOW()),
    ('Canvas (learning management systems)', NOW(), NOW()),
    ('captioning software', NOW(), NOW()),
    ('Capture One', NOW(), NOW()),
    ('Chef (tools for software configuration management)', NOW(), NOW()),
    ('Cisco', NOW(), NOW()),
    ('cloud monitoring and reporting', NOW(), NOW()),
    ('cloud security and compliance', NOW(), NOW()),
    ('cloud technologies', NOW(), NOW()),
    ('COBOL', NOW(), NOW()),
    ('Codenvy', NOW(), NOW()),
    ('CoffeeScript', NOW(), NOW()),
    ('cognitive computing', NOW(), NOW()),
    ('Common Lisp', NOW(), NOW()),
    ('computational fluid dynamics', NOW(), NOW()),
    ('computer equipment', NOW(), NOW()),
    ('computer forensics', NOW(), NOW()),
    ('computer graphics', NOW(), NOW()),
    ('computer programming', NOW(), NOW()),
    ('computer science', NOW(), NOW()),
    ('computer simulation', NOW(), NOW()),
    ('computer vision', NOW(), NOW()),
    ('configuration of the tote room hardware', NOW(), NOW()),
    ('control panel components', NOW(), NOW()),
    ('core banking software', NOW(), NOW()),
    ('CSS', NOW(), NOW()),
    ('data analytics', NOW(), NOW()),
    ('data engineering', NOW(), NOW()),
    ('data extraction, transformation and loading tools', NOW(), NOW()),
    ('data mining', NOW(), NOW()),
    ('data mining methods', NOW(), NOW()),
    ('data models', NOW(), NOW()),
    ('data protection', NOW(), NOW()),
    ('data science', NOW(), NOW()),
    ('data security principles', NOW(), NOW()),
    ('data storage', NOW(), NOW()),
    ('data visualisation software', NOW(), NOW()),
    ('data warehouse', NOW(), NOW()),
    ('database', NOW(), NOW()),
    ('database development tools', NOW(), NOW()),
    ('database management systems', NOW(), NOW()),
    ('database quality standards', NOW(), NOW()),
    ('DB2', NOW(), NOW()),
    ('decentralised identifiers', NOW(), NOW()),
    ('decentralized application frameworks', NOW(), NOW()),
    ('decision support systems', NOW(), NOW()),
    ('deep learning', NOW(), NOW()),
    ('desktop publishing', NOW(), NOW()),
    ('DevOps', NOW(), NOW()),
    ('digital identity management', NOW(), NOW()),
    ('digital systems', NOW(), NOW()),
    ('digital twin technology', NOW(), NOW()),
    ('distributed computing', NOW(), NOW()),
    ('distributed directory information services', NOW(), NOW()),
    ('distributed ledger technologies consensus protocols', NOW(), NOW()),
    ('distributed ledger technologies vulnerabilities', NOW(), NOW()),
    ('distributed ledger technology', NOW(), NOW()),
    ('domain name service', NOW(), NOW()),
    ('dredging consoles', NOW(), NOW()),
    ('Drupal', NOW(), NOW()),
    ('e-commerce systems', NOW(), NOW()),
    ('e-learning software infrastructure', NOW(), NOW()),
    ('Eclipse (integrated development environment software)', NOW(), NOW()),
    ('Edmodo', NOW(), NOW()),
    ('electronic business', NOW(), NOW()),
    ('Engrade', NOW(), NOW()),
    ('Erlang', NOW(), NOW()),
    ('ethical hacking principles', NOW(), NOW()),
    ('Filemaker (database management systems)', NOW(), NOW()),
    ('firmware', NOW(), NOW()),
    ('food waste monitoring systems', NOW(), NOW()),
    ('GIMP (graphics editor software)', NOW(), NOW()),
    ('graphics editor software', NOW(), NOW()),
    ('Groovy', NOW(), NOW()),
    ('Grovo', NOW(), NOW()),
    ('Hadoop', NOW(), NOW()),
    ('hardware components', NOW(), NOW()),
    ('hardware industry', NOW(), NOW()),
    ('hardware materials', NOW(), NOW()),
    ('hardware platforms', NOW(), NOW()),
    ('hardware testing methods', NOW(), NOW()),
    ('Haskell', NOW(), NOW()),
    ('hazard analysis and critical control points', NOW(), NOW()),
    ('human-computer interaction', NOW(), NOW()),
    ('hybrid control systems', NOW(), NOW()),
    ('hybrid model', NOW(), NOW()),
    ('IBM Informix', NOW(), NOW()),
    ('IBM InfoSphere DataStage', NOW(), NOW()),
    ('IBM InfoSphere Information Server', NOW(), NOW()),
    ('IBM WebSphere', NOW(), NOW()),
    ('ICT accessibility standards', NOW(), NOW()),
    ('ICT architectural frameworks', NOW(), NOW()),
    ('ICT debugging tools', NOW(), NOW()),
    ('ICT encryption', NOW(), NOW()),
    ('ICT environmental policies', NOW(), NOW()),
    ('ICT hardware specifications', NOW(), NOW()),
    ('ICT help platforms', NOW(), NOW()),
    ('ICT network cable limitations', NOW(), NOW()),
    ('ICT network routing', NOW(), NOW()),
    ('ICT network security risks', NOW(), NOW()),
    ('ICT network simulation', NOW(), NOW()),
    ('ICT networking hardware', NOW(), NOW()),
    ('ICT performance analysis methods', NOW(), NOW()),
    ('ICT power consumption', NOW(), NOW()),
    ('ICT problem management techniques', NOW(), NOW()),
    ('ICT process quality models', NOW(), NOW()),
    ('ICT recovery techniques', NOW(), NOW()),
    ('ICT security standards', NOW(), NOW()),
    ('ICT software specifications', NOW(), NOW()),
    ('ICT system integration', NOW(), NOW()),
    ('ICT system programming', NOW(), NOW()),
    ('ICT system user requirements', NOW(), NOW()),
    ('image recognition', NOW(), NOW()),
    ('incremental development', NOW(), NOW()),
    ('industrial software', NOW(), NOW()),
    ('Informatica PowerCenter', NOW(), NOW()),
    ('information architecture', NOW(), NOW()),
    ('information confidentiality', NOW(), NOW()),
    ('information extraction', NOW(), NOW()),
    ('information security strategy', NOW(), NOW()),
    ('information structure', NOW(), NOW()),
    ('integrated development environment software', NOW(), NOW()),
    ('inter-organisational middleware system', NOW(), NOW()),
    ('internet governance', NOW(), NOW()),
    ('Internet of Things', NOW(), NOW()),
    ('iOS', NOW(), NOW()),
    ('iterative development', NOW(), NOW()),
    ('Java (computer programming)', NOW(), NOW()),
    ('JavaScript', NOW(), NOW()),
    ('JavaScript Framework', NOW(), NOW()),
    ('Jenkins (tools for software configuration management)', NOW(), NOW()),
    ('John The Ripper (penetration testing tool)', NOW(), NOW()),
    ('Joomla', NOW(), NOW()),
    ('JSSS', NOW(), NOW()),
    ('Kali Linux', NOW(), NOW()),
    ('KDevelop', NOW(), NOW()),
    ('keywords in digital content', NOW(), NOW()),
    ('knowledge base', NOW(), NOW()),
    ('LAMS', NOW(), NOW()),
    ('LDAP', NOW(), NOW()),
    ('LESS', NOW(), NOW()),
    ('levels of software testing', NOW(), NOW()),
    ('LINQ', NOW(), NOW()),
    ('Lisp', NOW(), NOW()),
    ('Litmos', NOW(), NOW()),
    ('machine learning', NOW(), NOW()),
    ('machine translation', NOW(), NOW()),
    ('Maltego', NOW(), NOW()),
    ('MarkLogic', NOW(), NOW()),
    ('MATLAB', NOW(), NOW()),
    ('MDX', NOW(), NOW()),
    ('Metasploit', NOW(), NOW()),
    ('microchip scanners', NOW(), NOW()),
    ('microprocessors', NOW(), NOW()),
    ('Microsoft Access', NOW(), NOW()),
    ('Microsoft Visio', NOW(), NOW()),
    ('Microsoft Visual C++', NOW(), NOW()),
    ('microsystem test procedures', NOW(), NOW()),
    ('ML (computer programming)', NOW(), NOW()),
    ('mobile device management', NOW(), NOW()),
    ('mobile device software frameworks', NOW(), NOW()),
    ('mobile operating systems', NOW(), NOW()),
    ('Moodle', NOW(), NOW()),
    ('museum databases', NOW(), NOW()),
    ('MySQL', NOW(), NOW()),
    ('N1QL', NOW(), NOW()),
    ('Nessus', NOW(), NOW()),
    ('network management system tools', NOW(), NOW()),
    ('network standards', NOW(), NOW()),
    ('Nexpose', NOW(), NOW()),
    ('NoSQL', NOW(), NOW()),
    ('object-oriented modelling', NOW(), NOW()),
    ('Objective-C', NOW(), NOW()),
    ('ObjectStore', NOW(), NOW()),
    ('Octopus Deploy', NOW(), NOW()),
    ('office software', NOW(), NOW()),
    ('OmniPage', NOW(), NOW()),
    ('online analytical processing', NOW(), NOW()),
    ('Open source model', NOW(), NOW()),
    ('OpenEdge Advanced Business Language', NOW(), NOW()),
    ('OpenEdge Database', NOW(), NOW()),
    ('operating systems', NOW(), NOW()),
    ('optical character recognition software', NOW(), NOW()),
    ('Oracle Application Development Framework', NOW(), NOW()),
    ('Oracle Data Integrator', NOW(), NOW()),
    ('Oracle Relational Database', NOW(), NOW()),
    ('Oracle Warehouse Builder', NOW(), NOW()),
    ('Oracle WebLogic', NOW(), NOW()),
    ('Outsourcing model', NOW(), NOW()),
    ('OWASP ZAP', NOW(), NOW()),
    ('Parrot Security OS', NOW(), NOW()),
    ('Pascal (computer programming)', NOW(), NOW()),
    ('penetration testing tool', NOW(), NOW()),
    ('Pentaho Data Integration', NOW(), NOW()),
    ('Perl', NOW(), NOW()),
    ('PHP', NOW(), NOW()),
    ('PostgreSQL', NOW(), NOW()),
    ('principles of artificial intelligence', NOW(), NOW()),
    ('printed circuit boards', NOW(), NOW()),
    ('printed circuit boards testing methods', NOW(), NOW()),
    ('procurement of ICT network equipment', NOW(), NOW()),
    ('Prolog (computer programming)', NOW(), NOW()),
    ('Prototyping development', NOW(), NOW()),
    ('proxy servers', NOW(), NOW()),
    ('Puppet (tools for software configuration management)', NOW(), NOW()),
    ('Python (computer programming)', NOW(), NOW()),
    ('QlikView Expressor', NOW(), NOW()),
    ('quantum computing', NOW(), NOW()),
    ('query languages', NOW(), NOW()),
    ('R', NOW(), NOW()),
    ('Rapid application development', NOW(), NOW()),
    ('real-time computing', NOW(), NOW()),
    ('resource description framework query language', NOW(), NOW()),
    ('Ruby (computer programming)', NOW(), NOW()),
    ('Sakai', NOW(), NOW()),
    ('Salt (tools for software configuration management)', NOW(), NOW()),
    ('Samurai Web Testing Framework', NOW(), NOW()),
    ('sand blasting machine parts', NOW(), NOW()),
    ('SAP Data Services', NOW(), NOW()),
    ('SAP R3', NOW(), NOW()),
    ('SAS Data Management', NOW(), NOW()),
    ('SAS language', NOW(), NOW()),
    ('Sass', NOW(), NOW()),
    ('Scala', NOW(), NOW()),
    ('Schoology', NOW(), NOW()),
    ('scientific computing', NOW(), NOW()),
    ('scientific modelling', NOW(), NOW()),
    ('Scratch (computer programming)', NOW(), NOW()),
    ('screen reader', NOW(), NOW()),
    ('security panels', NOW(), NOW()),
    ('self-service technologies in tourism', NOW(), NOW()),
    ('service-oriented modelling', NOW(), NOW()),
    ('SketchBook Pro', NOW(), NOW()),
    ('Smalltalk (computer programming)', NOW(), NOW()),
    ('smart city features', NOW(), NOW()),
    ('smart contract', NOW(), NOW()),
    ('smart contract programming languages', NOW(), NOW()),
    ('software anomalies', NOW(), NOW()),
    ('software architecture models', NOW(), NOW()),
    ('software components libraries', NOW(), NOW()),
    ('software components suppliers', NOW(), NOW()),
    ('software design methodologies', NOW(), NOW()),
    ('software frameworks', NOW(), NOW()),
    ('software interaction design', NOW(), NOW()),
    ('software metrics', NOW(), NOW()),
    ('software UI design patterns', NOW(), NOW()),
    ('Solidity', NOW(), NOW()),
    ('solution deployment', NOW(), NOW()),
    ('SPARK', NOW(), NOW()),
    ('SPARQL', NOW(), NOW()),
    ('specialised astrology software', NOW(), NOW()),
    ('Spiral development', NOW(), NOW()),
    ('SQL', NOW(), NOW()),
    ('SQL Server', NOW(), NOW()),
    ('SQL Server Integration Services', NOW(), NOW()),
    ('STAF', NOW(), NOW()),
    ('standards for web-based e-learning', NOW(), NOW()),
    ('style sheet languages', NOW(), NOW()),
    ('supercomputing', NOW(), NOW()),
    ('Swift (computer programming)', NOW(), NOW()),
    ('Synfig', NOW(), NOW()),
    ('system backup best practice', NOW(), NOW()),
    ('system design', NOW(), NOW()),
    ('systems development life-cycle', NOW(), NOW()),
    ('systems theory', NOW(), NOW()),
    ('systems thinking', NOW(), NOW()),
    ('Taleo', NOW(), NOW()),
    ('task algorithmisation', NOW(), NOW()),
    ('Teradata Database', NOW(), NOW()),
    ('THC Hydra', NOW(), NOW()),
    ('tools for ICT test automation', NOW(), NOW()),
    ('tools for software configuration management', NOW(), NOW()),
    ('trading software', NOW(), NOW()),
    ('transmission technology', NOW(), NOW()),
    ('TripleStore', NOW(), NOW()),
    ('types of storage facilities', NOW(), NOW()),
    ('types of wire mesh', NOW(), NOW()),
    ('TypeScript', NOW(), NOW()),
    ('unified modelling language', NOW(), NOW()),
    ('unstructured data', NOW(), NOW()),
    ('usability engineering', NOW(), NOW()),
    ('Vagrant', NOW(), NOW()),
    ('VBScript', NOW(), NOW()),
    ('vehicle-to-everything technologies', NOW(), NOW()),
    ('virtual reality', NOW(), NOW()),
    ('Visual Basic', NOW(), NOW()),
    ('Vyper', NOW(), NOW()),
    ('Waterfall development', NOW(), NOW()),
    ('web analytics', NOW(), NOW()),
    ('web application security threats', NOW(), NOW()),
    ('web based collaborative platforms', NOW(), NOW()),
    ('web programming', NOW(), NOW()),
    ('web services', NOW(), NOW()),
    ('WebCMS', NOW(), NOW()),
    ('WhiteHat Sentinel', NOW(), NOW()),
    ('WildFly', NOW(), NOW()),
    ('Wireshark', NOW(), NOW()),
    ('WizIQ', NOW(), NOW()),
    ('WordPress', NOW(), NOW()),
    ('World Wide Web Consortium standards', NOW(), NOW()),
    ('Xcode', NOW(), NOW()),
    ('XQuery', NOW(), NOW());

